const PING = 0;
const ACCESS_DENIED = 1;

const LOAD_PLAYER_NAME_TAKEN = 2;
const LOAD_PLAYER_ALREADY_CONNECTED = 3;
const LOAD_PLAYER = 4;

const LOAD_GEAR = 5;
const STRIP_GEAR = 6;
const SAVE_PLAYER_AND_GEAR = 7;

const BANK_WITHDRAW = 8;
const BANK_DEPOSIT = 9;

export {
  PING,
  ACCESS_DENIED,
  LOAD_PLAYER_NAME_TAKEN,
  LOAD_PLAYER_ALREADY_CONNECTED,
  LOAD_PLAYER,
  LOAD_GEAR,
  STRIP_GEAR,
  SAVE_PLAYER_AND_GEAR,
  BANK_WITHDRAW,
  BANK_DEPOSIT
};
